#!/usr/bin/python

from ft.types import T_BOOL
from ft.internal import ftformat, input_values
from ft.error import panic
from ft.command import new_command

function, args = new_command("filter")

for value in input_values():
    result = function(value)

    if result.fttype == T_BOOL:
        if result.value:
            out = ftformat(value)
            if out:
                print(out)
    else:
        panic("The filter function needs to return a boolean")
