#!/usr/bin/python

from ft.types import T_ARRAY
from ft.internal import ftformat, input_values
from ft.command import new_command


fn, args = new_command("map")

for value in input_values():
    if value.fttype == T_ARRAY and args.column is not None:
        idx = args.column - 1
        value.value[idx] = fn(value.value[idx])
        result = value
    else:
        result = fn(value)

    out = ftformat(result)

    if out:
        print(out)
