#!/usr/bin/python

import argparse

from functools import partial

from ft.types import T_ARRAY
from ft.internal import ftformat, input_values
from ft.functions import commands
from ft.error import panic


parser = argparse.ArgumentParser(description='map')
parser.add_argument('command', help='todo')
parser.add_argument('args', help='todo', nargs='*')
parser.add_argument('--column', '-c', type=int, help='column')

args = parser.parse_args()

try:
    command = commands[args.command]
except KeyError:
    panic("Command not found: '{}'".format(args.command))

# Partially apply the command

if len(args.args) > 0:
    command = partial(command, *args.args)

for value in input_values():
    if value.fttype == T_ARRAY and args.column is not None:
        idx = args.column - 1
        value.value[idx] = command(value.value[idx])
        result = value
    else:
        result = command(value)

    out = ftformat(result)

    if out:
        print(out)
