#!/usr/bin/python

import sys
import argparse

from functools import partial

from fttypes import T_BOOL, T_STRING, TypedValue
from command import panic, ftformat
from functions import commands

parser = argparse.ArgumentParser(description='filter')
parser.add_argument('command', help='todo')
parser.add_argument('args', help='todo', nargs='*')

args = parser.parse_args()

try:
    command = commands[args.command]
except KeyError:
    panic("Command not found: '{}'".format(args.command))

# Partially apply the command

if len(args.args) > 0:
    command = partial(command, *args.args)

for line in sys.stdin:
    if line.endswith("\r\n"):
        line = line[:-2]
    if line.endswith("\n"):
        line = line[:-1]

    line = line.strip()
    line_typed = TypedValue(line, T_STRING)

    out = command(line_typed)
    if out.fttype == T_BOOL:
        if out.value:
            print(ftformat(line_typed))
    else:
        panic("The filter command needs to return a boolean")
