#!/usr/bin/python

import sys
import argparse

from functools import partial
from fttypes import TypedValue, T_STRING
from command import panic, ftformat
from functions import commands


parser = argparse.ArgumentParser(description='map')
parser.add_argument('command', help='todo')
parser.add_argument('args', help='todo', nargs='*')
parser.add_argument('--column', '-c', type=int, help='column')

args = parser.parse_args()

try:
    command = commands[args.command]
except KeyError:
    panic("Command not found: '{}'".format(args.command))

# Partially apply the command

if len(args.args) > 0:
    command = partial(command, *args.args)

for line in sys.stdin:
    if line.endswith("\r\n"):
        line = line[:-2]
    if line.endswith("\n"):
        line = line[:-1]

    line = line.strip()

    column = 1
    if args.column:
        column = args.column
        parts = line.split("\t")
    else:
        parts = [line]

    try:
        value = parts[column - 1]
    except IndexError:
        panic("Column index out of range")

    value_typed = TypedValue(value, T_STRING)

    result = command(value_typed)

    out = ftformat(result)

    parts[column - 1] = out
    print("\t".join(parts))
