#!/usr/bin/python

import argparse

from functools import partial
from command import panic, ftformat, input_values
from functions import commands


parser = argparse.ArgumentParser(description='map')
parser.add_argument('command', help='todo')
parser.add_argument('args', help='todo', nargs='*')
parser.add_argument('--column', '-c', type=int, help='column')

args = parser.parse_args()

try:
    command = commands[args.command]
except KeyError:
    panic("Command not found: '{}'".format(args.command))

# Partially apply the command

if len(args.args) > 0:
    command = partial(command, *args.args)

for value in input_values():
    result = command(value)
    out = ftformat(result)
    print(out)
